### ISSUE TITLE
0.3版本新增的登录界面中错误跳转问题

### ISSUE THREAD

**Issue by yyngfive** [cubiccm/PotatoPlus#12]
在0.3版本中，如果在新增的登陆界面中输入学号和密码之后再点击“统一认证”按钮，会自动通过旧系统登录。因为我是20级的，所以会登陆失败。如果学号和密码输入框都是空的，点击统一认证会正常跳转到统一身份认证界面。感觉这样的做法有些别扭，点击统一身份认证按钮以后，无论输入框是否有内容，都会跳转到统一身份认证界面。我认为这样比较符合直觉。

我的浏览器：Edge 92.0.902.84
插件来源：微软Edge拓展商店 v0.3 2021-8-28日

**Comment by cubiccm** [comment]
Hello @yyngfive:

这是一个已知的问题，已经在一个[过去的Commit](https://github.com/cubiccm/PotatoPlus/commit/1be9dff331556fc7afc6b147c17c57c42a9a450a)中修复，并即将随下次版本更新提交至商店。

一个临时的workaround：可以每次手动关闭新设计的提示框；或是直接取消勾选登录页面下方紫色工具栏的“验证码识别”一项，这样下次就不会再自动弹出提示框了。

感谢你的反馈！如果你在更新到这次Commit之后的版本后还存在此问题，请重新打开这一issue。
