### ISSUE TITLE
选课系统的显示似乎有问题

### ISSUE THREAD

**Issue by cxzxcht** [cubiccm/PotatoPlus#13]
您好，2021年9月13日我在教务平台上选课时发现体育课和通识课显示没有课程，但关闭插件后可以正常显示。
     插件PotatoPlus在谷歌扩展插件中心下载，电脑系统为win7。

**Comment by cubiccm** [comment]
Hello Ansicht:

我刚刚用自己的账号测试了一下，通识课初选和体育初选都是可以正常加载列表的。不过我已经不能进行体育初选，所以显示的是没有课程。注意“聚合选课”中只能选择补选课程（除体育），所以请通过一般的入口进行课程初选；如果你不是通过“聚合选课”选择也遇到相同的问题，麻烦补充一下相关的细节：

1. 你所使用的PotatoPlus版本是多少？你的浏览器版本（Chrome？）是否为较新的版本？
2. 显示“没有课程”后，屏幕上有没有显示相关报错信息？
3. 上述情况是否持续存在？偶尔的、并无关联性的出现可能是教务系统的问题。
4. 如果方便的话，能否提供一下你的年级？可能某些年级的课程显示不太相符。

如果你不想公开部分信息，你也可以发邮件给我（illimosity@gmail.com）。
一个workaround：试试使用学校的新版选课系统（xk.nju.edu.cn）。

**Comment by cubiccm** [comment]
@cxzxcht：我刚刚发现了一个可能导致较旧版本的浏览器（Chrome <85, Firefox <77, Edge <85）加载列表失败的问题，并在 [commit](https://github.com/cubiccm/PotatoPlus/commit/5164dc79a527e6bed6b981c8f020f8cdca0e1d3d) 中修改了部分代码，将会在稍后的版本更新中发布到商店。如果你也遇到了同样的问题，可以先尝试更新浏览器到最新版本。
