### ISSUE TITLE
关于课程时间筛选的request

### ISSUE THREAD

**Issue by Bobo-alcazar** [cubiccm/PotatoPlus#15]
您好。
目前该插件的课程时间筛选似乎仅允许负面筛选，这在想察看某一时段某课程有哪写老师上时很不方便。（尤其是通修课）希望能增加正面筛选功能。

**Comment by cubiccm** [comment]
Alcazar 你好：

可以尝试一下使用搜索框进行筛选，目前支持直接输入课程名、教师等字段，并可以用空格分隔。此外，还可以试试用拼音首字母快速搜索。

如果想看某一时间段，可以点击课程时间筛选器中的"All"全选，然后点击你想要的时间就可以允许这些时间的课程。

上面的功能是否能解决你的问题？如果无法解决或者觉得步骤过于复杂，请在下面详细描述一下～
