### ISSUE TITLE
专业选课貌似会挡住“确定”选项

### ISSUE THREAD

**Issue by Marcos-cc** [cubiccm/PotatoPlus#17]
开发者您好，在专业选课的过程中，选中专业课后，右下角的“确定”按钮会被紫色的横幅（从左下角开始的那个紫色横幅）挡住，没法点击“确定”，今早选课选中后半天找不到确定，结果发现被挡住了。
浏览器：chrome
系统：win10 20H2
插件版本：0.3.3

**Comment by cubiccm** [comment]
这是旧版本的残留设计，可以点击工具栏左侧的按钮收起工具栏～
