### ISSUE TITLE
体育选课退选提示"操作类型不合法"

### ISSUE THREAD

**Issue by lyc8503** [cubiccm/PotatoPlus#18]
https://github.com/cubiccm/PotatoPlus/blob/9e587cbfadd358fd08d159bf108aa0442953ec41/js/pjw-modes.js#L334

应该是此处的判断出现问题.
未开启插件时抓包发现体育选课退选请求地址为 https://xk.nju.edu.cn/xsxkapp/sys/xsxkapp/elective/deleteVolunteer.do, 而插件请求了 volunteer.do

**Comment by cubiccm** [comment]
感谢反馈！

粗略看了眼代码，可能是没有考虑到除了“专业课”一栏的“退选”功能，稍晚些会尝试修复。

另外，新版选课系统下的功能未经大量测试，且存在不少已知问题，所以除了测试用途以外，还是不太推荐在新系统开启插件。

顺祝新学期愉快！
