### ISSUE TITLE
验证码识别

### ISSUE THREAD

**Issue by heren1229** [cubiccm/PotatoPlus#19]
现在统一身份认证也要验证码了  
请问大佬能不能做一个自动识别呢  
因为教务系统的验证码识别确实太好用了

**Comment by cubiccm** [comment]
旧教务系统的验证码和统一身份认证的不太一样，在这个项目中识别验证码也只是比较简单地对图片做了一些划分和去杂处理并与训练样本匹配，不太能直接用于识别统一身份认证的验证码，所以暂时不能直接移植过去。

后续如果有时间的话可能会再做考虑，用一些比较现代的方法实现😂
