### ISSUE TITLE
查看不了学生信息

### ISSUE THREAD

**Issue by heren1229** [cubiccm/PotatoPlus#20]
![image](https://user-images.githubusercontent.com/100464233/177298582-d1723781-0e12-408a-8e86-bc5f987a0237.png)
个人信息-学生信息查看不了,点击三个选项也没有反应  
希望修正,感谢

**Comment by cubiccm** [comment]
一个暂时的 workaround：强制刷新浏览器页面，内容就会正常显示了。强制刷新的方式随浏览器不同，可能是 长按浏览器刷新键 / Shift+F5 / Shift+command+R / control+command+R 等等。

这个问题其实很早之前就出现过，是因为教务系统的这个页面自带较早版本的 jQuery，而插件使用了较新版本的 jQuery。如果不“强制刷新”，浏览器会使用现有的缓存而导致原本网页的代码优先加载。类似的问题可以在教务系统主页反映出来：插件正常情况下会拦截首页弹出的 alert 框，并以下方通知栏的方式弹出；但由于浏览器有时会使用缓存，页面中的 javascript 会先于插件代码执行，导致拦截不成功。这个问题原本已经部分得到解决，但升级 Manifest v3 之后由于浏览器不再允许插件动态嵌入代码至页面，这些问题又再一次出现了。目前在 Manifest v3 下我没有找到办法解决这个问题。

总之，在我找到解决方案之前，可以先用上面的 workaround 暂时解决一下。

顺便，这个项目的代码有些古老和混乱，重构又太耗时耗力，加上旧教务系统即将退休，目前没什么动力更新内容了，可能最多还会有些小修补吧，所以别对我能找到解决方案抱有太大希望hhh
