### ISSUE TITLE
20221学期新选课系统中无法正常选课退课

### ISSUE THREAD

**Issue by lollipop190** [cubiccm/PotatoPlus#21]
目前20221学期选课只在新的选课系统中有，potatoplus在新的选课系统中无法正常退选课。
（老的教务系统中没有预选课了。。猜测后面补选的时候可能也只在新的系统中进行了。。。）

选课会提示：选择《xx课程》失败：教学班不在开放选课轮次中
退课会提示：退选《xx课程》失败：操作不合法（跨专业选课），退选《xx课程》失败：教学班不在开放选课轮次中（专业选课）

个人猜测是新的选课系统的api改变，恳请大佬完善一下，不胜感激。

**Comment by cubiccm** [comment]
感谢反馈，已经在新版本中修复。其实不是API改变，是原本代码的逻辑太混乱了，导致专业课可以选择的时候出现问题。

另外还是建议在新系统中不要启用 PotatoPlus，以免出现错误影响抢课。

**Comment by lollipop190** [comment]
辛苦，再次感谢
