### ISSUE TITLE
课程操作按钮点击无反应（最新的0.3.8版本）

### ISSUE THREAD

**Issue by lollipop190** [cubiccm/PotatoPlus#24]
大佬好，最新的版本更新之后，课程操作按钮点击没有反应，无论是选课还是退课，看了下网络检查器，按钮点击之后好像也没有发送出网络请求。

**Comment by cubiccm** [comment]
Hi lollipop:

感谢你的反馈！这个问题已经在源码中修复，稍后会发布新版本。
